lib/naive_dice_web/router.ex
defmodule NaiveDiceWeb.Router do
  use NaiveDiceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NaiveDiceWeb do
    pipe_through :browser

    get "/", EventController, :index

    resources("/events", EventController, only: [:index, :show]) do
      resources("/tickets", TicketController, only: [:new, :create])

      resources("/guests", GuestController, only: [:index])
      delete "/guests/reset", GuestController, :reset_guests
    end

    # event_id is captured on a Ticket already - no need to have it in a route
    resources("/tickets", TicketController, only: [:edit, :show])
  end

  scope "/payment", NaiveDiceWeb do
    pipe_through(:api)

    post "/intent", PaymentController, :intent
    post "/webhook", PaymentController, :webhook
  end

  # Other scopes may use custom stacks.
  # scope "/api", NaiveDiceWeb do
  #   pipe_through :api
  # end
end

lib/naive_dice/events/ticket.ex
defmodule NaiveDice.Events.Ticket do
  @moduledoc """
  This schema represents a purchased ticket

  TODO: should we use the same schema to represent a pending reservation?
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}

  schema "tickets" do
    field :user_name, :string
    field :event_id, :integer
    # pending, purchased
    field :state, :string
    field :intent, :string

    timestamps()
  end

  @doc false
  def changeset(ticket, attrs \\ %{}) do
    ticket
    |> cast(attrs, [:user_name, :event_id, :state, :intent])
    |> validate_required([:user_name, :event_id])
    |> unique_constraint(:user_name,
      name: :tickets_event_id_user_name,
      message: "ticket already exists"
    )
  end
end

lib/naive_dice_web/controllers/ticket_controller.ex
defmodule NaiveDiceWeb.TicketController do
  use NaiveDiceWeb, :controller
  alias NaiveDice.Events

  require Logger

  action_fallback(NaiveDiceWeb.FallbackController)

  # STEPS OF THE WIZARD

  @doc """
  STEP 1: Renders an empty form with user name input
  That's an entry point for the booking flow.
  """
  def new(conn, %{"event_id" => event_id}) do
    with {:ok, event} <- Events.get_event_by_id(event_id) do
      {:ok, tickets_sold} = Events.tickets_sold(event)
      remaining_tickets = event.allocation - tickets_sold

      # see https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html
      render(conn, "new.html", %{
        changeset: Events.new_ticket_changeset(),
        event: event,
        remaining_tickets: remaining_tickets
      })
    end
  end

  @doc """
  STEP 2: Renders the Stripe payment form
  """
  def edit(conn, %{"id" => ticket_id}) do
    with {:ok, ticket} <- Events.get_ticket_by_id(ticket_id) do
      case ticket.state do
        "purchased" -> conn |> redirect(to: Routes.ticket_path(conn, :show, ticket_id))
        "pending" -> render(conn, "edit.html", %{ticket: ticket})
      end
    end
  end

  @doc """
  STEP 3: Renders the confirmation / receipt / thank you screen
  """
  def show(conn, %{"id" => ticket_id}) do
    with {:ok, ticket} <- Events.get_ticket_by_id(ticket_id) do
      render(conn, "show.html", %{ticket: ticket})
    end
  end

  # TRANSITIONS BETWEEN WIZARD STEPS

  @doc """
  Reserves a ticket for 5 minutes
  """
  def create(conn, %{"event_id" => event_id, "ticket" => %{"user_name" => user_name}}) do
    with {:ok, event} <- Events.get_event_by_id(event_id) do
      case Events.reserve_ticket(event, user_name) do
        {:ok, ticket} ->
          Logger.info(
            "New ticket created, id: #{inspect(ticket.id)}, user_name: #{
              inspect(ticket.user_name)
            }"
          )

          conn |> redirect(to: Routes.ticket_path(conn, :edit, ticket.id))

        _error ->
          conn
          |> put_flash(:info, "All tickets sold.")
          |> redirect(to: Routes.event_path(conn, :show, event.id))
      end
    end
  end
end

lib/naive_dice_web/views/ticket_view.ex
defmodule NaiveDiceWeb.TicketView do
  use NaiveDiceWeb, :view
end

lib/naive_dice_web/templates/ticket/edit.html.eex
<!--
Renders a payment form.
Capturing a payment "updates" the ticket (marks it as a "paid" one).
-->

<div class="all-bold">

    <p>Nice to meet you <%= @ticket.user_name %>!</p>

    <p>
    We reserved your ticket for 5 minutes
    <br>
    Please complete the purchase using a test credit card
    </p>

</div>
<%= if @ticket.state != "purchased" do %>
  <form id="payment-form" class="sr-payment-form" data-ticket-id="<%= @ticket.id %>"">
    <div class="sr-combo-inputs-row">
      <div class="sr-input sr-card-element" id="card-element"></div>
    </div>
    <div class="sr-field-error" id="card-errors" role="alert"></div>
    <button id="submit-payment">
      <div class="spinner hidden" id="spinner"></div>
      <span id="button-text">Pay</span><span id="order-amount"></span>
    </button>
  </form>
<% end %>

lib/naive_dice_web/templates/ticket/new.html.eex
<!--
Renders an empty form with user name input. That's an entry point for the booking flow.
-->

<h1>
  DON'T MISS YOUR TICKETS
  <br>
  FOR <%= @event.title %>
</h1>

<p>
only <%= @remaining_tickets %> ticket(s) left
</p>

<br>
<br>
<br>
<br>

<%= form_for @changeset, Routes.event_ticket_path(@conn, :create, @event.id), fn f -> %>
  <div class="col-md-6 mb-3">
    <label>YOUR NAME </label>
    <br>
    <%= text_input f, :user_name, required: true, class: "form-control", placeholder: "e.g John Doe" %>

    <br>

    <%= submit "Reserve ticket for 5 minutes", class: "btn btn-primary" %>
  </div>
<% end %>

lib/naive_dice_web/templates/ticket/show.html.eex
<!--
Renders a successfully purchased ticket.
-->

<h1>Congratulations <%= @ticket.user_name %>!</h1>

<p>
    You've been added to the
    <a class="blue" href="<%= Routes.event_guest_path(@conn, :index, @ticket.event_id) %>">list of guests</a>
</p>